-- Criar novo BD 
CREATE DATABASE GREENHOUSE;

-- ULTILIZANDO O BD
USE GREENHOUSE;

-- CRIANDO UMA TABELA 		
CREATE TABLE`GREENHOUSE`.PLANTS (
	PLANT_NAME CHAR(30) NOT NULL,
    SENSOR_VALUE FLOAT DEFAULT NULL, 
    SENSOR_EVENT TIMESTAMP NOT NULL 
		DEFAULT CURRENT_TIMESTAMP on 
        UPDATE CURRENT_TIMESTAMP,
	SENSOR_LEVEL CHAR(5) DEFAULT NULL, 
    PRIMARY KEY PK_PLANT_NAME(PLANT_NAME) 
    );
    
-- COMANDOS DML DE INSERÇÃO DE DADOS 
INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Orquidea', 10, 'HIGH');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Pinheiro', 30, 'MED');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Rosa', 25, 'HIGH');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Violeta', 35, 'LOW');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Suculenta', 45, 'HIGH');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Cravo', 70, 'MED');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Margarida', 60, 'HIGH');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Azedinha', 50, 'LOW');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Cannabis', 40, 'HIGH');

INSERT INTO GREENHOUSE.PLANTS
(PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL)
VALUES('Salsinha', 20, 'MED');

-- EXECUTANDP COMANDOS DQL - SELECT
-- CONSULTANDO TUDO DA TABELA 
SELECT * FROM GREENHOUSE. PLANTS;

-- ESPECIFICANDO APENAS COLUNAS DESEJADAS 
SELECT PLANT_NAME, SENSOR_EVENT
FROM PLANTS;

-- APLICAR FILTROS NOS REGISTROS DE DADOS 
SELECT * 
FROM PLANTS
WHERE SENSOR_LEVEL = 'HIGH'
AND SENSOR_VALUE >= 10 AND SENSOR_VALUE <= 20;

SELECT *
FROM PLANTS 
WHERE SENSOR_LEVEL IN ('HIGH', 'LOW');

-- CLAUSULA DE ORDENAÇÃO 
SELECT *
FROM PLANTS
WHERE SENSOR_VALUE < 420
ORDER BY SENSOR_VALUE DESC;

-- FUNÇOES DE AGRUPAMENTO 
SELECT COUNT(*), SENSOR_LEVEL
FROM PLANTS 
GROUP BY SENSOR_LEVEL;

-- COMANDO UPDATE PARA ATUALIZAR REGISTROS DE DADOS
 SELECT * FROM PLANTS;
 UPDATE PLANTS
 SET SENSOR_VALUE = 90, SENSOR_LEVEL = 'HIGH'
 WHERE PLANT_NAME = 'Babosa';
 
 -- APAGANDO REGISTROS DA TABEAL DO BANCO DE DADOS
 DELETE FROM PLANTS
 WHERE PLANT_NAME = 'Coqueiro';
 
 
 
 

