CREATE DATABASE UNOESC_BANK;

CREATE TABLE CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE CONTA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NRO_CONTA VARCHAR(10) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_ID_CLIENTE_CONTA FOREIGN KEY (ID_CLIENTE)
		REFERENCES CLIENTT(ID)
);

CREATE TABLE TRANSAÇÃO (
	ID INT NOT NULL auto_increment PRIMARY KEY,
    ID_CONTA INT NOT NULL ,
    TIPO_TRANSAÇÃO INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
    VALOR FLOAT NOT NULL
);

-- DEFININDO UMA FK POSTERIORMENTE A CRIAÇÃO DA TABELA 
ALTER TABLE TRANSACAO
ADD FOREIGN KEY (ID_CONTA) 
REFERENCES CONTA (ID);
